version: '3.9'

services:
    database: 
        image: mysql
        container_name: firs_project
        command: --default-allthentication-plugin=mysql_native_password
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_DATABASE: 'adonis'
        ports:
            - '3306':3306'
            